fos_rest:
    disable_csrf_role:    ~
    access_denied_listener: ~
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    routing_loader:
        default_format:       ~
        include_format:       true
    view:
        view_response_listener: force
        serialize_null:       false
        default_engine:       twig
        failed_validation:    400
        empty_content:        204
        exception_wrapper_handler:  FOS\RestBundle\View\ExceptionWrapperHandler
        jsonp_handler:
            callback_param:       callback
            mime_type:            application/javascript+jsonp
    body_converter:
        enabled: false
        validate: true
        validation_errors_argument:  validationErrors
    cache_dir:            %kernel.cache_dir%/fos_rest
    service:
        router:               router
        templating:           templating
        serializer:           jms_serializer.serializer
        view_handler:         fos_rest.view_handler.default
        inflector:            fos_rest.inflector.doctrine
        validator:            validator
    serializer:
        version:              ~

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'