# Assetic Configuration
assetic:
    debug:          false # %kernel.debug%
    use_controller: false
    java: "/usr/bin/java"
    read_from:      %kernel.root_dir%/../web
    write_to:       %kernel.root_dir%/../web
    #bundles:        [] # disable bundles parsing

    filters:
        cssrewrite: ~
        yui_js:  { jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.rmzamora-build.jar" }
        yui_css: { jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.rmzamora-build.jar" }
        closure: { jar: "%kernel.root_dir%/Resources/java/google.closure.jar" }

    assets:
        # see http://sonata-project.org/blog/2012/5/15/assetic-package-configuration
        #
#        sonata_jqueryui_js:
#            inputs:
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.core.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.widget.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.mouse.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.draggable.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.droppable.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.resizable.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.selectable.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.sortable.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.accordion.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.autocomplete.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.button.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.datepicker.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.dialog.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-blind.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-bounce.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-clip.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-drop.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-explode.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fade.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-fold.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-highlight.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-pulsate.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-scale.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-shake.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-slide.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.effect-transfer.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.menu.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.position.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.progressbar.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.slider.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.spinner.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tabs.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/jquery.ui.tooltip.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/ui/i18n/jquery-ui-i18n.js

#            filters:
#                - yui_js

#        sonata_jqueryui_css:
#            inputs:
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jqueryui/themes/flick/jquery-ui.css
#
#            filters:
#                - cssrewrite
#                - yui_css
#
#        sonata_formatter_js:
#            inputs:
#                # do not uncomment this, ckeditor behave badly when compacted...
#                #- %kernel.root_dir%/../web/bundles/sonataformatter/vendor/ckeditor/ckeditor.js
#                - %kernel.root_dir%/../web/bundles/sonataformatter/vendor/markitup-markitup/markitup/jquery.markitup.js
#                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/markdown/set.js
#                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/html/set.js
#                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/textile/set.js
#
#            filters:
#                - yui_js
#
#        sonata_formatter_css:
#            inputs:
#                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/skins/sonata/style.css
#                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/markdown/style.css
#                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/html/style.css
#                - %kernel.root_dir%/../web/bundles/sonataformatter/markitup/sets/textile/style.css
#
#            filters:
#                - cssrewrite
#                - yui_css
#
        sonata_admin_js:
            inputs:
                - %kernel.root_dir%/../web/bundles/rzadmin/js/modernizr.custom.42016.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery/jquery.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jqueryui/js/jqueryui.custom.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/browser-detect/jquery.browser.detect.js
                - %kernel.root_dir%/../web/bundles/fosjsrouting/js/router.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/js/bootstrap.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/select/js/select.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/tabdrop/js/tabdrop.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/datepicker/js/bootstrap-datepicker.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/timepicker/js/timepicker.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/datetimepicker/js/datetimepicker.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/modal/js/modalmanager.js
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/modal/js/modal.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/uniform/uniform.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/foo-table/js/footable.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/multi-select/js/multiselect.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/multi-select/js/quicksearch.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/blockui/jquery.blockui.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/gritter/js/gritter.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/qtip2/js/qtip.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/form/jquery.form.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/nicescroll/jquery.nicescroll.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/touch-punch/jquery.touch-punch.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/slimscroll/jquery.slimscroll.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/icheck/jquery.icheck.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/masonry/masonry.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/imagesloaded/imagesloaded.min.js
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/select2/select2.js
                - %kernel.root_dir%/../web/bundles/rzadmin/js/lib/sprintf.js
                - %kernel.root_dir%/../web/bundles/rzadmin/js/rzadmin-base.js
                - %kernel.root_dir%/../web/bundles/rzfieldtype/js/rzadmin-fieldtype.js
                - %kernel.root_dir%/../web/bundles/rzdoctrineormadmin/js/rzadmin-many-assoc.js
                - %kernel.root_dir%/../web/bundles/rzdoctrineormadmin/js/rzadmin-one-assoc.js
            filters:
                - closure
#
        sonata_admin_css:
            inputs:
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/css/bootstrap.min.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/css/bootstrap-responsive.min.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/modal/css/modal.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/tabdrop/css/tabdrop.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/modal/css/modal.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/multi-select/css/multiselect.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/gritter/css/gritter.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/qtip2/css/qtip.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/select/css/select.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/datepicker/css/datepicker.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/timepicker/css/timepicker.css
                - %kernel.root_dir%/../web/bundles/rmzamorabootstrap/plugins/datetimepicker/css/datetimepicker.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/icheck/skins/minimal/_all.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/icheck/skins/square/_all.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/icheck/skins/flat/_all.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/icheck/skins/line/_all.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/icheck/skins/polaris/polaris.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/icheck/skins/futurico/futurico.css
                - %kernel.root_dir%/../web/bundles/rmzamorajquery/jquery-plugins/select2/select2.css
                - %kernel.root_dir%/../web/bundles/rzadmin/css/font.css
                - %kernel.root_dir%/../web/bundles/rzadmin/css/style.css
                - %kernel.root_dir%/../web/bundles/rzadmin/css/rz-style.css
                - %kernel.root_dir%/../web/bundles/rzadmin/css/themes.css
                - %kernel.root_dir%/../web/bundles/rzadmin/css/rz-theme.css
            filters:
                - cssrewrite
                - yui_css
#
#        sonata_front_js:
#            inputs:
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/jquery/dist/jquery.js
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.js
#                - %kernel.root_dir%/../web/bundles/sonataproduct/js/product.js
#                - %kernel.root_dir%/../web/bundles/sonatacore/js/base.js
#                - %kernel.root_dir%/../web/bundles/sonatacore/select2/select2.min.js
#                - %kernel.root_dir%/../web/bundles/sonatademo/js/demo.js
#
#            filters:
#                - yui_js
#
#        sonata_front_css:
#            inputs:
#                - %kernel.root_dir%/../web/bundles/sonataadmin/vendor/bootstrap/dist/css/bootstrap.min.css
#                - %kernel.root_dir%/../web/bundles/sonatacore/select2/select2.css
#                - %kernel.root_dir%/../web/bundles/mopabootstrap/css/datepicker.css
#                - %kernel.root_dir%/../web/bundles/sonatademo/css/demo.css
#
#            filters:
#                - cssrewrite
#                - yui_css