hwi_oauth_redirect:
    resource: "@RzOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

rz_oauth_connect:
    resource: "@RzOAuthBundle/Resources/config/routing/connect.xml"

facebook_login:
    pattern: /login/check-facebook

twitter_login:
    pattern: /login/check-twitter

google_login:
    pattern: /login/check-google

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#Sonata Profile Edition
sonata_user_profile:
    #use oauth controller
    resource: "@RzOAuthBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

sonata_media_gallery:
    resource: '@RzMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

sonata_media_media:
    resource: '@RzMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_page_ajax:
    resource: '@SonataPageBundle/Resources/config/routing/page.xml'
    prefix: /

sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /page

sonata_media_pixlr:
    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
    prefix: /admin/media

sonata_qa:
    resource: "@SonataQABundle/Resources/config/routing/qa.xml"
#_imagine:
#    resource: .
#    type:     imagine

rz_media_rest_service:
    type: rest
    resource: '@RzMediaBundle/Resources/config/REST/media_service_rest.yml'
    prefix: /admin/api/rzmedia

blog:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /blog

blog:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /blog

fos_comment:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /comments
    defaults: { _format: html }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"