rz_classification:
  providers:
    category:
      default_context: default
      contexts:
          default:  # the default context is mandatory
              provider: rz_classification.provider.category.default
              default_template: default
              templates:
                  default:
                      path: RzClassificationBundle:Category:list.html.twig
                      name: Default
          news:
              provider: rz_classification.provider.category.news
              default_template: default
              templates:
                  default:
                      path: RzNewsBundle:Post:category_list_default.html.twig
                      name: Default
                  blog:
                      path: RzNewsBundle:Post:category_list_blog.html.twig
                      name: Blog
                  event:
                      path: RzNewsBundle:Post:category_list_event.html.twig
                      name: Event
    collection:
      default_context: default
      contexts:
          default:  # the default context is mandatory
              provider: rz_classification.provider.collection.default
              default_template: default
              templates:
                  default:
                      path: RzNewsBundle:Collection:list.html.twig
                      name: Default
          news:
              provider: rz_classification.provider.collection.news
              default_template: default
              templates:
                  default:
                      path: RzNewsBundle:Post:collection_list_default.html.twig
                      name: Default
                  blog:
                      path: RzNewsBundle:Post:collection_list_blog.html.twig
                      name: Blog
                  event:
                      path: RzNewsBundle:Post:collection_list_event.html.twig
                      name: Event
    tag:
      default_context: default
      contexts:
          default:  # the default context is mandatory
              provider: rz_classification.provider.tag.default
              default_template: default
              templates:
                  default:
                      path: RzClassificationBundle:Tag:list.html.twig
                      name: Default
          news:
              provider: rz_classification.provider.tag.news
              default_template: default
              templates:
                  default:
                      path: RzNewsBundle:Post:tag_list_default.html.twig
                      name: Default