rz_news:
  blocks:
    collection:
        class: Rz\NewsBundle\Block\PostByCollectionBlockService
        templates:
          collection_default_block:
            name: Default Collection Block Template
            path: RzNewsBundle:Block:post_by_collection_list.html.twig
  settings:
    news_pager_max_per_page: 2
    ajax_pagination: true
  default_collection: event
  collections:
      default:  # the default context is mandatory
          provider: rz_news.provider.default
          default_template: default
          templates:
              default:
                  path: RzNewsBundle:Post:view.html.twig
                  name: Default
      blog:
          provider: rz_news.provider.default
          default_template: default
          templates:
              default:
                  path: RzNewsBundle:Post:view.html.twig
                  name: Default
      event:
          provider: rz_news.provider.event
          default_template: default
          templates:
              default:
                  path: RzNewsBundle:Post:view.html.twig
                  name: Default
              Event:
                  path: RzNewsBundle:Post:view_event.html.twig
                  name: Event